# Generated by Django 6.0 on 2025-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('course', models.CharField(choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('BUS', 'Business'), ('ART', 'Arts')], default='CS', max_length=3)),
            ],
        ),
    ]
